import type { FastifyReply, FastifyRequest } from 'fastify';

/**
 * Request ID Middleware
 * Ensures request ID is returned in response headers for correlation
 *
 * The request ID is already generated by Fastify via genReqId in server.ts
 * This middleware simply adds it to the response header for client tracking
 */
export async function requestIdMiddleware(request: FastifyRequest, reply: FastifyReply) {
  // Add request ID to response header
  reply.header('X-Request-Id', request.id);
}
